version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: safepay-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: safepay_guardian
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: safepay-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  ml-service:
    build: ./ml-service
    container_name: safepay-ml-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  backend:
    build: ./backend
    container_name: safepay-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/safepay_guardian
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=safepay_super_secret_jwt_key_2026_demo
      - ML_SERVICE_URL=http://ml-service:8000
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
      - redis
      - ml-service

  frontend:
    build: ./frontend
    container_name: safepay-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data:
  redis-data:
